# Generated by Django 5.1.1 on 2024-09-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=50)),
                ('subheading', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/slider')),
            ],
        ),
    ]
