# Generated by Django 5.1.1 on 2024-09-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_sliderimage_slideritem_delete_slider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='image',
            field=models.ImageField(default=1, upload_to='slider_images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SliderImage',
        ),
    ]
