# Generated by Django 5.1.1 on 2024-10-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_billing_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='Address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='billing',
            name='Email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='billing',
            name='Phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='billing',
            name='city',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='billing',
            name='fristName',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='billing',
            name='lastName',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
